---

- name: install certbot from repo
  apt:
    name: certbot
    state: latest
    default_release: "{{ ansible_distribution_release }}-backports"
  when: certbot__install_from_repo

- debug:
    msg: "{{ certbot__bin }} args: '{{ certbot__args | join(' ') }}'"
  when: certbot__debug | default(False)

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
