---

- name: install certbot from repo
  apt:
    name: certbot
    state: latest
    default_release: "{{ ansible_distribution_release }}-backports"
  when: certbot__install_from_repo

- name: create certbot script dir
  file:
    path: "{{ certbot__scriptdir }}"
    state: directory
    mode: 0700

- name: create cert gen script
  template:
    src: certbot.j2
    dest: "{{ certbot__scriptdir }}/certbot.sh"
    mode: 0700

- name: create certs
  command: "{{ certbot__scriptdir }}/certbot.sh"

- name: get list of live certs
  command: "{{ certbot__bin }} certificates"
  register: livecerts
- debug:
    msg: "{{ livecerts.stdout_lines }}"


# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
